<?php

use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
            DB::table('comevents')->insert([
                [   
                    'division'=> "Future Trend", 
                    'desciption'=> "บริษัท ไลค์มี จำกัดนั้นเป็นบริษัทที่มีแบร์ดหลากหลาย ทั้ง InfographicThailand , AomMoeny , ถุงเงิน Family , Future Trends",
                    'quantity' => 'รับหลายอัตรา',
                    'jobtime' => '10.00 - 18.00',
                    'reward' => 0,
                    'havereward' => 0,
                    'formreward' => 0,
                    'staff_id' => 1,
                    'requirement'=> "Graphic Designer,UI Designer",
                    'img'=> "/uploads/images/comevents/1581243398.png",
                    'question1'=> "ถ้าหากต้องทำงานล่วงเวลา หรือมีภาระงานที่มากสามารถทำงานได้หรือไม่",
                    'question2'=> "ชอบทำงานลักษณะไหน",
                    'enddate'=> '2020-12-05',
                    'com_id'=> 1,
                    'job_id'=>8,
                    'invite'=> 5,
                ],
                [   
                    'division'=> "Uppercuz trainee #10", 
                    'desciption'=> "ศึกครานี้ใหญ่หลวงนักเตรียมตัวให้พร้อมเหล่าผู้กล้าทั้งหลาย เพราะการคัดเลือก นักศึกษาฝึกงาน Uppercuz trainee #10กำลังจะมาแล้ว! ",
                    'quantity' => 'รับหลายอัตรา',
                    'jobtime' => '10.00 - 18.00',
                    'havereward' => 0,
                    'reward' => 0,
                    'formreward' => 0,
                    'staff_id' => 2,
                    'requirement'=> "Graphic Designer,UX Designer",
                    'img'=> "/uploads/images/comevents/uppercuz.jpg",
                    'question1'=> "Question01",
                    'question2'=> "Question02",
                    'enddate'=> '2020-12-05',
                    'com_id'=> 2,
                    'job_id'=>8,
                    'invite'=> 5,
                ],
                [   
                    'division'=> "Rabbit Digital Group", 
                    'desciption'=> "Rabbit Digital Group ขอชวนน้องๆพร้อมจั๊มป์ด้วยกันกับ LAB Rabbit รุ่นที่ 1 โครงการกระต่ายลองงาน สร้างคุณให้กลายเป็นกระต่ายดัดแปลงที่แข็งแกร่งกว่าเดิม!",
                    'quantity' => 'รับหลายอัตรา',
                    'jobtime' => '10.00 - 18.00',
                    'reward' => 250,
                    'havereward' => 1,
                    'formreward' => '/ ต่อวัน',
                    'staff_id' => 3,
                    'requirement'=> "UI Designer,Graphic Desinger",
                    'img'=> "/uploads/images/comevents/RabbitTale.jpg",
                    'question1'=> "Question01",
                    'question2'=> "Question02",
                    'enddate'=> '2020-12-05',
                    'com_id'=> 3,
                    'job_id'=>8,
                    'invite'=> 5,
                ],
                [   
                    'division'=> "Grappik", 
                    'desciption'=> "ถ้าคุณรักงานออกแบบและพร้อมคิดงานเจ๋งๆให้สมองได้ระเบิดไอเดียออกมา รีบมาสมัครฝึกงานกับเราได้เลยได้ทำงานจริง ลุยสนามจริง เจ็บจริง เจอสนามการทำงานของชีวิตจริง",
                    'quantity' => 'รับหลายอัตรา',
                    'jobtime' => '10.00 - 18.00',
                    'reward' => 0,
                    'havereward' => 0,
                    'formreward' => 0,
                    'staff_id' => 4,
                    'requirement'=> "Graphic Designer",
                    'img'=> "/uploads/images/comevents/Grappik.png",
                    'question1'=> "Question01",
                    'question2'=> "Question02",
                    'enddate'=> '2020-12-05',
                    'com_id'=> 4,
                    'job_id'=>8,
                    'invite'=> 5,
                ],
                [   
                    'division'=> "Inspire digital", 
                    'desciption'=> "รับสมัครนักศึกษาฝึกงาน สามารถออกแบบ Website Design ได้,ทำภาพเคลื่อนไหว motion graphicได้,มีความเข้าใจเรื่องของ CI และมีความคิดสร้างสรรค์ ทำงานเป็นระเบียบ",
                    'quantity' => 'รับหลายอัตรา',
                    'jobtime' => '10.00 - 18.00',
                    'reward' => 300,
                    'havereward' => 1,
                    'formreward' => '/ ต่อวัน',
                    'staff_id' => 5,
                    'requirement'=> "Graphic Designer",
                    'img'=> "/uploads/images/comevents/Inspire digital.jpg",
                    'question1'=> "Question01",
                    'question2'=> "Question02",
                    'enddate'=> '2020-12-05',
                    'com_id'=> 5,
                     'job_id'=>8,
                    'invite'=> 5,
                ],
                [   
                    'division'=> "kidyer",  
                    'desciption'=> "โอกาสสำหรับน้องๆ การทำงานแบบ Survivors เอาชีวิตรอดในเมืองกรุง สำหรับคนที่มี “ความคิด” เยอะ แต่ไม่รู้จะเอาไปปล่อยที่ไหน Kidyers ซึ่งทำงานด้าน Digital Creative Agency เปิดรับสมัครนักศึกษาฝึกงาน",
                    'quantity' => 'รับหลายอัตรา',
                    'jobtime' => '10.00 - 18.00',
                    'reward' => 0,
                    'havereward' => 0,
                    'formreward' => 0,
                    'staff_id' => 6,
                    'requirement'=> "Motion Graphic",
                    'img'=> "/uploads/images/comevents/kidyer.jpg",
                    'question1'=> "Question01",
                    'question2'=> "Question02",
                    'enddate'=> '2020-12-05',
                    'com_id'=> 6,
                    'job_id'=>8,
                    'invite'=> 5,
                ],
                [   
                    'division'=> "Web Programmer / System Analyst",  
                    'desciption'=> "บริษัท บางกอก เว็บ โซลูชั่น จำกัด เกิดจากการรวมกลุ่มของทีมงานมืออาชีพที่มีความเชี่ยวชาญด้านโปรแกรมเมอร์ , ออกแบบเว็บไซต์ , พัฒนาระบบ Software ",
                    'quantity' => 'รับหลายอัตรา',
                    'jobtime' => '9.00 - 17.30',
                    'reward' => 6000,
                    'havereward' => 1,
                    'formreward' => '/ ต่อเดือน',
                    'staff_id' => 7,
                    'requirement'=> "Front-end Developer,Back-end Developer",
                    'img'=> "/uploads/images/comevents/bangkokweb.png",
                    'question1'=> "Question01",
                    'question2'=> "Question02",
                    'enddate'=> '2020-12-05',
                    'com_id'=> 7,
                    'job_id'=>7,
                    'invite'=> 5,
                ],
                [   
                    'division'=> "รับนักศึกษาด้านการเขียน Web (Computer, IT, Programmer, Web design",  
                    'desciption'=> "บริษัทดำเนินธุรกิจด้านการอบรมให้กับองค์กรเอกชน หน่วยงานราชการ และองค์กรอิสระ ทั้งในและต่างประเทศ รวมทั้งให้บริการการโค้ชส่วนตัวสำหรับเจ้าของกิจการและผู้บริหารที่ต้องการความสุขและความสำเร็จในทุกๆ ด้านของชีวิตอย่างยั่งยืน",
                    'quantity' => 'รับหลายอัตรา',
                    'jobtime' => '08.30 - 17.30',
                    'reward' => 0,
                    'havereward' => 0,
                    'formreward' => 0,
                    'staff_id' => 8,
                    'requirement'=> "Back-end Developer",
                    'img'=> "/uploads/images/comevents/miracle.jpg",
                    'question1'=> "Question01",
                    'question2'=> "Question02",
                    'enddate'=> '2020-12-05',
                    'com_id'=> 8,
                    'job_id'=>7,
                    'invite'=> 5,
                ],
                [   
                    'division'=> "CI Internship - IT",  
                    'desciption'=> "Bosch Group ออกแบบขึ้นเพื่อเพิ่มความสะดวกสบายในการดำรงชีวิต ด้วยการพัฒนาโซลูชันต่างๆ ที่มีทั้งความทันสมัยควบคู่กับประโยชน์ใช้สอย",
                    'quantity' => '1',
                    'jobtime' => '09.00 - 18.00',
                    'reward' => 500,
                    'havereward' => 1,
                    'formreward' => '/ ต่อวัน',
                    'staff_id' => 9,
                    'requirement'=> "Back-end Developer",
                    'img'=> "/uploads/images/comevents/bosch.jpg",
                    'question1'=> "Question01",
                    'question2'=> "Question02",
                    'enddate'=> '2020-12-05',
                    'com_id'=> 9,
                    'job_id'=>7,
                    'invite'=> 5,
                ],
                
                
               
                
                
            ]);

    }
}
