// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

export const FETCH_COMEVENT = 'FETCH_COMEVENT'
export const FETCH_COMEVENT_SHOW = 'FETCH_COMEVENT_SHOW'
export const FETCH_USER_JOIN = 'FETCH_USER_JOIN'
export const FETCH_JOINREQS = 'FETCH_JOINREQS'
export const FETCH_MAKE_EVENT = 'FETCH_MAKE_EVENT'

export const FETCH_USERINFO = 'FETCH_USERINFO'
export const FETCH_DAIRY = 'FETCH_DAIRY'
export const FETCH_DAIRY_SHOW = 'FETCH_DAIRY_SHOW'
export const FETCH_MAKE_DAIRY = 'FETCH_MAKE_DAIRY'
