// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'


export const FETCH_COMEVENT = 'FETCH_COMEVENT'
export const FETCH_STAFFS = 'FETCH_STAFFS'
export const FETCH_SHOWSTAFFS = 'FETCH_SHOWSTAFFS'
export const FETCH_COMEVENT_SHOW = 'FETCH_COMEVENT_SHOW'
export const FETCH_USER_JOIN = 'FETCH_USER_JOIN'
export const FETCH_JOINREQS = 'FETCH_JOINREQS'
export const FETCH_STUDENT_JOIN = 'FETCH_STUDENT_JOIN'
export const FETCH_SHOWSTUDENT_JOIN = 'FETCH_SHOWSTUDENT_JOIN'
export const FETCH_JOB = 'FETCH_JOB'
export const FETCH_COMJOB = 'FETCH_COMJOB'
export const FETCH_TYPE = 'FETCH_TYPE'
export const FETCH_STUCONFIRM = 'FETCH_STUCONFIRM'
export const FETCH_SHOWDETAILREVIEW = 'FETCH_SHOWDETAILREVIEW'
export const FETCH_INTERNCONFIRM = 'FETCH_INTERNCONFIRM'
export const FETCH_GETCOMEVENT = 'FETCH_GETCOMEVENT'

 
export const FETCH_ALLSTUDENT = 'FETCH_ALLSTUDENT'
export const FETCH_MAJORS = 'FETCH_MAJORS'
export const FETCH_ALLDAIRY = 'FETCH_ALLDAIRY'
export const FETCH_CALENDAR = 'FETCH_CALENDAR'
export const FETCH_TCOURSE = 'FETCH_TCOURSE'


export const FETCH_PROVINCE = 'FETCH_PROVINCE'
export const FETCH_AUTHPROVINCE = 'FETCH_AUTHPROVINCE'
export const FETCH_ALLUNIVERSITY = 'FETCH_ALLUNIVERSITY'
export const FETCH_AUTHALLUNIVERSITY = 'FETCH_AUTHALLUNIVERSITY'

export const FETCH_USERINFO = 'FETCH_USERINFO' 
export const FETCH_USERSHOW = 'FETCH_USERSHOW'
export const FETCH_COURSES = 'FETCH_COURSES'

export const FETCH_STUDENT_INFO_SHOW = 'FETCH_STUDENT_INFO_SHOW'
export const FETCH_DAIRY = 'FETCH_DAIRY'
export const FETCH_DAIRY_SHOW = 'FETCH_DAIRY_SHOW'
export const FETCH_MAKE_DAIRY = 'FETCH_MAKE_DAIRY'
export const FETCH_ALLDAIRY_SHOW = 'FETCH_ALLDAIRY_SHOW'

